### ISSUE TITLE
design for the outboards.

### ISSUE THREAD

**Issue by simbav911** [RaulBejarano/Ultimate-Toroidal-Propeller-Generator#10]
I wish I could design something like this, for the ship. Can you add a future to move blades like in the photo? Thanks
![render (1)](https://user-images.githubusercontent.com/42268591/224484755-3f36fbf0-a37d-4dd0-9205-e51306564680.png)

**Comment by RaulBejarano** [comment]
Hi, right now there is no plans to move in that way but, I will check your boat propeller in case there is a easy way to achieve that.

Also, this is a open source project and if you want to contribute you are welcome 😃

**Comment by magicsmoke** [comment]
I'd like to +1 this and would be happy to test.

**Comment by RaulBejarano** [comment]
I am closing this feature request because the project has evolved, and developing it as it stands now would be quite complicated. Perhaps a new project could be created to address this specific functionality. Thank you for your attention and collaboration.
