### ISSUE TITLE
Add hollow airfoil profile

### ISSUE THREAD

**Issue by wierni** [RaulBejarano/Ultimate-Toroidal-Propeller-Generator#12]

**Comment by wierni** [comment]
Add an airfoil profile, par example the hollow curve like an GWS prop for better performance

**Comment by RaulBejarano** [comment]
Hi @wierni. I've answered first issue #13 that ask for the same as you. I'm going to mark this as a duplicate.

Thanks for your enhacement proposal.

**Comment by RaulBejarano** [comment]
Duplicate of #13
