### ISSUE TITLE
optional hub recess

### ISSUE THREAD

**Issue by filip-smid** [RaulBejarano/Ultimate-Toroidal-Propeller-Generator#14]
Would it be possible to add configurable recess in hub, so that it can "slip over" thicker tapped shaft ?
effectively it would be second configurable hub removed from the original one..

**Comment by RaulBejarano** [comment]
Hello, I'm not sure what are you asking for. Can you sketch it?

**Comment by filip-smid** [comment]
![image](https://user-images.githubusercontent.com/79947606/235744481-f7de2bfe-a24f-497c-9c18-e9a099aa8e71.png)
which would result is similar extrusion:
![image](https://user-images.githubusercontent.com/79947606/235744610-cc9b8342-4768-4655-90e5-8c2ef6db5997.png)

**Comment by filip-smid** [comment]
this way it can slip over a thick shaft that only has a slim thread protruding / tapped shaft end, or it can be put over the whole outrunner motor

**Comment by filip-smid** [comment]
ok, code change needed:
![image](https://user-images.githubusercontent.com/79947606/236693862-367c55ba-57a0-49c2-b632-827f0b4b4a42.png)
![image](https://user-images.githubusercontent.com/79947606/236693912-6bd4a2a3-4038-45f6-94be-2775fd6294af.png)
where nose = thickness of the face that stays behind
nose_dia = diameter of the shaft it slips over

Do I do pull request? Or you manage it all yourself ?

**Comment by filip-smid** [comment]
and here's the result
![image](https://user-images.githubusercontent.com/79947606/236693988-0ba91176-1aa3-406f-8661-459200524af9.png)
